### ISSUE TITLE
如何將 audio alone 檔案上傳到 YouTube ?

### ISSUE THREAD

**Issue by zinojeng** [JimLiu/whisper-subtitles#4]
只是 audio alone 檔案，如何使用這個程式呢？Thanks

**Comment by JimLiu** [comment]
建议您直接使用WhisperX：https://colab.research.google.com/drive/1E4vVbMUAMNjiCxZvCHS0JUj9YEiQP8zl?usp=sharing#scrollTo=_BdFUVixu-7p
